version: "3"
services:
  registry:
    image: registry:latest
    restart: unless-stopped
    volumes:
      - ./registry:/var/lib/registry
    ports:
      - 127.0.0.1:5100:5000
      # felix-cluster
      - 169.254.1.70:5100:5000
