apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    ports:
      websecure:
        tls:
          certResolver: leresolver
      # web:
      #   redirectTo: websecure
    persistence:
      # persists the /data directory
      enabled: true
    logs:
      general:
        level: DEBUG
    additionalArguments:
      - --certificatesresolvers.leresolver.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.leresolver.acme.email=me@alexjball.com
      # Please note that this is the staging Let's Encrypt server.
      # Once you get things working, you should remove that whole line altogether.
      # - --certificatesresolvers.leresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.leresolver.acme.storage=/data/acme.json
