name: Lint And Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-repo
      - name: Lint
        if: always()
        run: yarn lint
      - name: Test
        if: always()
        run: yarn test
